name: Test React App
on: push
jobs:
  test-my-react:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test  