name: Test React App
on: push
jobs:
  test-my-react:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install

      - name:
        run: npm run lint

  build:
    needs: test-my-react
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: build app
        run: npm run build
      - name: upload build
        run: echo "Qurbon tit"